spring.application.name=hr-oauth
# server.port=${PORT:0}
server.port=8082

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# added lated
test.config=teste-valor
jwt.secret=TesteJWT
oauth.client.name=cliente-teste
oauth.client.secret=segredo-teste